import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import firebaseui from "firebaseui"
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { NavBar } from "@/components/nav-bar";
import { NavigationProgress } from "@/components/navigation-progress"
import { Suspense } from "react";

//var firebase = require('firebase');

const firebaseConfig = {
  apiKey: "AIzaSyBWDytFvpHPBIX8HBkdV_OY76hekfhvpdc",
  authDomain: "talent-vault-e1c5a.firebaseapp.com",
  projectId: "talent-vault-e1c5a",
  storageBucket: "talent-vault-e1c5a.firebasestorage.app",
  messagingSenderId: "85641447974",
  appId: "1:85641447974:web:8027b0eec64d6e119f74e7",
  measurementId: "G-DGVTV567JZ"
};

//const app = initializeApp(firebaseConfig);
//const analytics = getAnalytics(app);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//const fbUI = new firebaseui.auth.AuthUI(firebase.auth());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
        <Suspense fallback={null}>
          <NavigationProgress />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
